import type { NextPage } from 'next'
import Head from 'next/head'
import Minutes from '../components/Minutes'
import Internet from '../components/Internet'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Hawking Bros</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='main'>
        <h1 className='title'>Настройте тариф</h1>
        <Minutes />
        <span>Используйте вместе с тарифом</span>
        <Internet />
      </main>
    </div>
  )
}

export default Home
